title: Codegazers
description: Bitacora
author: Javier Ramírez
theme_author: agus makmun
theme_github: https://github.com/agusmakmun
about: Javier Ramírez Urea - Technology Advocate, Docker Captain, Docker Certificate Associate and Docker Certified Instructor
disqus_shortname: frjaraur
avatar_url: /static/img/avatar.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/frjaraur"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/frjaraur"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/frjaraur"
    - icon: fa-github
      link: "https://github.com/codegazers"
share:
  twitter_username: frjaraur
  #fb_appid: 1749788565247320

urls:
    - text: About Me
      url: https://about.me/frjaraur
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://codegazers.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
